### ISSUE TITLE
Uploading new samples ? 

### ISSUE THREAD

**Issue by johncohn** [stevenaeola/node-red-contrib-music#102]
Steven,
    I've had a great Time using node-red contrib-music in the build of this 30 foot keyboard I'm redoing. It works fantastic. Now I have some sounds I would like to upload in .wav or aiff. Do you have any example / instructions of how I can do that ? Thanks !
-jc

**Comment by stevenaeola** [comment]
Hi John,
  great to hear that it's working well for you. The most recent version has a synth type "user-sample". Any samples you want to use you (.wav or .aif) you should put in the "uploads" folder within node-red-contrib-music (which will be inside your .ned-red/node_modules). If that doesn't work or doesn't make sense then let me know.

There are at least two further bits of functionality that could be usefully added:
 1. Allow upload of samples via the web interface
 2.Specify the pitch of the sample (as a midi value) so that the sample would be tuneable

If either of those are important to you then let me know - add them as issues and I should be able to sort them out reasonably quickly

**Comment by johncohn** [comment]
Steven
   Thank you very much for the quick response. I think this gives me what 
I need to get working. I am definitely Interested in the two enhancements… 
Specifically 2.. I would definitely need to be able to pitch the sound 
samples To fit the keyboard application…. Being able to upload them easily 
from a web form would be super great as well…I'd be happy and honored to 
be your alpha tester  !

-jc


John Cohn Ph.D, 
IBM Fellow , MIT-IBM Watson AI Lab
phone 802-578-0985



From:   Steven Bradley ***@***.***>
To:     stevenaeola/node-red-contrib-music 
***@***.***>
Cc:     john cohn ***@***.***>, Author 
***@***.***>
Date:   04/05/2021 04:59 AM
Subject:        [EXTERNAL] Re: [stevenaeola/node-red-contrib-music] 
Uploading new samples ?  (#102)



Hi John, great to hear that it's working well for you. The most recent 
version has a synth type "user-sample". Any samples you want to use you 
(.wav or .aif) you should put in the "uploads" folder within 
node-red-contrib-music (which will be 
Hi John,
great to hear that it's working well for you. The most recent version has 
a synth type "user-sample". Any samples you want to use you (.wav or .aif) 
you should put in the "uploads" folder within node-red-contrib-music 
(which will be inside your .ned-red/node_modules). If that doesn't work or 
doesn't make sense then let me know.
There are at least two further bits of functionality that could be 
usefully added:
Allow upload of samples via the web interface
2.Specify the pitch of the sample (as a midi value) so that the sample 
would be tuneable
If either of those are important to you then let me know - add them as 
issues and I should be able to sort them out reasonably quickly
