### ISSUE TITLE
Beat synchronization using arbitrary data via tap-tempo input

### ISSUE THREAD

**Issue by Noir-** [stevenaeola/node-red-contrib-music#50]
I see that you are working on some beat synchronization feature between different instances of node-red.

I want to ask if you would consider a "tap tempo" input as a good addition. This would allow users to generate the BPM out of almost everything which can interact with node-red.

My use-case would be picking up the BPM from external MIDI input.

This could improve the current architecture of the beat master/slave nodes as well, since node-red already provides UDP input nodes. (Or is this because of performance issues?)

**Comment by stevenaeola** [comment]
Yes that sounds like a good idea. I'm actually reworking the synchronised inputs using WebSockets, which should have performance close to UDP but with the reliability of TCP. Also many wireless networks don't allow UDP.

But adding a way of setting the bpm for a beat node is probably a separate issue anyway. Would you imagine the input taps being sent as outputs of the beat node, or to just to set the bpm ahead of a start input? Or both?

**Comment by Noir-** [comment]
My idea was that the tap-tempo function is a feature of the beat node. I think the minimum viable product would be an option which allows treating all input which is not related with controlling the node as a source for determining the tempo. I don't see much additional value in a dedicated node for tap-tempo.

I create a new issue regarding master/slave synchronization.

**Comment by stevenaeola** [comment]
I agree re integrating tempo tapping into beat node. I did a bit more thinking about what this would mean depending on whether the beat had started yet or not, how many taps minimum etc. I came up with this proposal:

Incoming events need to have payload "tap" to be considered for setting the bpm. I don't want to treat all incoming events as taps, in case we want to add further functionality/runtime configuration later.

Minimum number of beats required to tap to set tempo is configurable, default 4. Fewer taps than this won't set the tempo. More taps than this will continue setting the tempo with the last n taps. Taps greater than 6 seconds apart will be counted as separate sequences (minimum bpm setting is 10).

Have an autostart option (default true) such that once the required number of taps have been done the beat starts if it hasn't already.

Sequences of taps when the beat is running update the bpm once the minimum number is reached.

So overall default behaviour is that you tap 1-2-3-4 and then the beat starts with that tempo.

After that bpm can still be set with an incoming message with topic bpm. This allows for sliders etc also to control the tempo.

Could possibly have an additional output to report changes of bpm, so that sliders etc can be linked in to update automatically with taps, if that makes sense.

What do you think?

**Comment by Noir-** [comment]
This sounds great!

The reasoning behind my approach where all data can be used to determine the BPM was, that every modification of the message trough different nodes might add additional overhead which might increase the latency. But maybe I'm overestimating things here.

My detailed use case (only a rough POC is done yet) is that I want to receive notes from a hardware sequencer. In software I want to use the sequencer node of this project for triggering some logic for DMX and Philips Hue lighting control. So I have a pretty long signal chain here: Hardware note -> MIDI -> USB stack -> node-red midi -> node-red sequencer -> node-red dtls stack -> hue bridge -> Zigbee.

**Comment by stevenaeola** [comment]
I think the latency introduced would only be a handful of milliseconds, probably not noticeable in lighting. Not sure though
