### ISSUE TITLE
Master - slave synchronization via websockets

### ISSUE THREAD

**Issue by Noir-** [stevenaeola/node-red-contrib-music#51]
In the issue #50 @stevenaeola stated that he is reworking the current implementation with websockets for better reliability and compatibility.

The idea sounds great. However, there are multiple nodes available which are dealing with all kind of domain specific websocket input. But there's no node just for plain websocket support. Perhaps there could be an extra node-contrib package created which deals with plain websockets for better reuse.

**Comment by stevenaeola** [comment]
I think there is a plain websocket node available in the input and output palette section, but I'm actually using websockets internally in the code (using  <https://www.npmjs.com/package/ws>) rather than requiring extra nodes. Hopefully it will be finished soon and integrated into the main node-red-contrib-music package. 

I have used plain websockets for joining up node-red-contrib-music to some visualisations using <http://processingjs.org/> which was quite good fun.

**Comment by Noir-** [comment]
Duh, you are right. There's a websocket node already there. Maybe it came with a upgrade and I was suffering change blindness. NVM then :smile: 

Nice hint for processing btw. I'm really into doing visual stuff with lighting and video atm.
