### ISSUE TITLE
Reconnection of synth requires redeployment

### ISSUE THREAD

**Issue by richrarobi** [stevenaeola/node-red-contrib-music#82]
After a power cut... and after restarting scsynth using the script, I found that the synth nodes were not working, giving errors on supercollider, and needed to be reloaded (i.e. load a different one then reload the first).

It is actually easier to delete the whole flow and reload it from a text (json) backup.

I wonder if there is any way that this can be automated, so that an environment could be "unattended". e.g. Is there something like a status check I could do in node-red?

All of the above are on Linux systems (sc and node-red on a pi4 (buster)) as well as nr elsewhere, e.g Mint Linux.

**Comment by stevenaeola** [comment]
Hi there. Yes, if scsynth is restarted without restarting the synth nodes then there will be a problem for sample-based synths because the sample is loaded into the buffer at deployment time, not play time. The quick fix for this is usually just to redeploy all the nodes, which will resend the samples and everything should be fine. In recent versions of node-red there is a 'Restart Flows' option at the bottom of the 'Deploy' pulldown. Could you check if that works for you?

Even if it does it would be much nicer in general if this didn't happen, and I should write some docs about debugging, including this advice, so I will open a separate issue on that. 

In the medium term I would like to be able to change synths dynamically, which would require more smarts on the scsynth side than we currently have, so I will think about that some more and leave this issue open until I have done that or decided it can't be done.

In the longer term I plan to make a browser-only version/option which would route sound through the WebAudio API (like gibber does). This would probably be less performant but would allow for a no-installation version, and be more robust to restart issues like this one. I don't plan to add this as an issue just yet as it's a bit longer term than that and I don't want to add loads of issues that will be unresolved for quite a while yet. Thoughts on that are welcome.

**Comment by richrarobi** [comment]
Thanks for the quick response! I will try the restart flows option. I don't tend to use web audio, so can't really add much there. I get some awesome sounds out of a pi4 via Pimoroni Phat Beat into some old Sony mini hi-fi speakers.

In passing, I tried the flow on a different system, (easy as it uses OSC) and noticed that the synths available didn't include the ones from Sonic, which is totally understandable.
It might be worth documenting (maybe I didn't find it yet?) which ones are supplied in which package? Although it isn't a real issue.

Incidentally, the response from Node-Red and your music node is markedly quicker than via the sonic pi gui. e.g. If you tried live playing via LAN and sonic . . . the delay would be too obvious (probably the X gui slows it down).

Which brings me to another idea - just going to look at the sonic code(!) - I installed superC using sonic (currently 3.2.2_4 ) - and use your scsynth.sh to load it up. I would really love  to be able to load their gui "next to" the node red code. I think some kind of "quantum entanglement" gets invoked, and it all falls to pieces. I believe the GUI should be a separate module for this to have any chance of working. (I don't like Ruby ( too cryptic), but I am going to look anyway). Port number soup probably?

**Comment by richrarobi** [comment]
I tried the restart flows option - it does work - Thanks, that makes life easier!
I got carried away, because sonic-pi install doesn't include the scide, - I installed supercollider using the sc instructions - I tried over the top of sonic-pi (so far it seems I have broken that....oops!)

Also, I found that to get remote connections working I had to add -B 0.0.0.0  to the scsynth startup line in your script. The default for supercollider is 127.0.0.1 , I haven't yet found how to change that.

**Comment by stevenaeola** [comment]
This fix requires your flows to be changed: you need to replace the osc + udp nodes with a single supercollider node. I'm pulling together a 2.0 release in which this will be the main new (breaking) component. You're very welcome to try out this new functionality, although it's not reflected in the docs yet
